export default [
  { text: "chính phủ", value: 64, },
  { text: "đất nước", value: 11, },
  { text: "lực lượng", value: 16, },
  { text: "cơ quan", value: 17, },
  { text: "đối tượng", value: 10, },
  { text: "cộng sản", value: 144, },
  { text: "dân tộc", value: 12, },
  { text: "Đảng", value: 177, },
  { text: "chống dịch", value: 45, },
  { text: "địa phương", value: 19, },
  { text: "pay", value: 13, },
  { text: "chính trị", value: 32, },
  { text: "an ninh", value: 22, },
  { text: "nhiệm vụ", value: 35, },
  { text: "hành vi", value: 24, },
  { text: "miền Nam", value: 38, },
  { text: "nhà nước", value: 70, },
  { text: "quốc gia", value: 20, },
  { text: "chửi", value: 10, },
  { text:"chống phá", value: 30, },
  { text:"tham nhũng", value: 20 },
  { text:"Việt á", value: 40, },
  { text:"Kinh tế", value: 20, },
  { text:"biển đảo", value: 30, },
  { text:"Trường Sa", value: 20, },
  { text:"chủ tịch nước", value: 23, },
  { text:"nhân sự", value: 5, },
  { text:"quyền lực", value: 8, },
  { text:"ngoại giao", value: 17, },
  { text:"nhiệm kỳ", value: 5, },
  { text:"93 năm", value: 33, },
  { text:"thành lập", value: 39, },
  { text:"hội nghị", value: 22, },
  { text:"phong trào", value: 10, },
  { text:"yêu nước", value: 26, },
  { text:"quốc tế", value: 15, },
  { text:"Đông dương", value: 13, },
  { text:"An nam", value: 12, },
  { text:"cách mạng", value: 43, },
  { text:"bác Hồ", value: 54, },
  { text:"thời cơ", value: 24, },
  { text:"tổng bí thư", value: 24, },
  { text:"Nguyễn Phú Trọng", value: 12, },
  { text:"Nguyễn Ái Quốc", value: 29, },
  { text:"phê bình", value: 27, },
  { text:"xung đột", value: 33, },
  { text:"vũ trang", value: 28, },
  { text:"đường lối", value: 22, },
  { text:"thắng lợi", value: 38, },
  { text:"hội nhập", value: 24, },
  { text:"phát triển", value: 13, },
  { text:"thách thức", value: 22, },
  { text:"hòa bình", value: 13, },
  { text:"khó khăn", value: 22, },
  { text:"bản chất", value: 10, },
  { text:"vẻ vang", value: 8, },
  { text:"phát huy", value: 5, },
  { text:"truyền thống", value: 8, },
  { text:"nguồn lực", value: 12, },
  { text:"chiến lược", value: 8, },
  { text:"phấn khởi", value: 12, },
  { text:"đại sứ quán", value: 3, },
  { text:"Đảng ủy", value: 24, },
  { text:"kỷ niệm", value: 25, },
  { text:"hữu nghị", value: 12, },
  { text:"2023", value: 15, },
  { text:"nhiệm vụ", value: 18, },
  { text:"duy trì", value: 3, },
  { text:"huyện ủy", value: 12, },
  { text:"song phương", value: 18, },
  { text:"văn minh", value: 8, },
  { text:"thịnh vượng", value: 17, },
  { text:"trung ương", value: 14, },
  { text:"bộ trưởng", value: 3, },
  { text:"chức vụ", value: 8, },
  { text:"cán bộ", value: 28, },
  { text:"công tác", value: 15, },
  { text:"Nguyễn Xuân Phúc", value: 7, },
  { text:"quốc phòng", value: 20, },
  { text:"củng cố", value: 7, },
  { text:"tăng cường", value: 3, },
  { text:"hợp tác", value: 5, },
  { text:"đối ngoại", value: 17, },
  { text:"thúc đẩy", value: 4, },
  { text:"văn hóa", value: 5, },
  { text:"giáo dục", value: 6, },
  { text:"khoa học", value: 3, },
  { text:"kỹ thuật", value: 2, },
  { text:"tiềm năng", value: 7, },
  { text:"Đảng viên", value: 17, },
  { text:"2022", value: 17, },
  { text:"phong trào", value: 9, },
  { text:"tích cực", value: 4, },
  { text:"thành tích", value: 8, },
  { text:"ASEAN", value: 13, },
  { text:"vui mừng", value: 7, },
  { text:"phấn khởi", value: 7, },
  { text:"thường vụ", value: 14, },
  { text:"họp báo", value: 3, },
  { text:"tư tưởng", value: 15, },
  { text:"đạo đức", value: 17, },
  { text:"anh hùng", value: 22, },
  { text:"vận động", value: 15, },
  { text:"phát huy", value: 22, },
  { text:"vi phạm", value: 16, },
  { text:"nghiêm trọng", value: 14, },
  { text:"liệt sĩ", value: 6, },
  { text:"hy sinh", value: 9, },
  { text:"cống hiến", value: 12, },
  { text:"quyết tâm", value: 8, },
  { text:"bất ổn", value: 17, },
  { text:"đốt lò", value: 29, },
  { text:"thượng tầng", value: 115, },
  { text:"Quốc hội", value: 18, },
  { text:"bất thường", value: 10, },
  { text:"trung thành", value: 15, },
];
